apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: spring-music
  annotations:
    github.com/project-slug: coyte/spring-music
spec:
  type: other
  lifecycle: unknown
  owner: coyte
