apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: nl-tanzu-java-web-app
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: spring-music
    apps.tanzu.vmware.com/has-tests: "false"
spec:
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
    - name: testing_pipeline_matching_labels
      value:
        apps.tanzu.vmware.com/language: java
  source:
    git:
      url: https://github.com/coyte/spring-music
      ref:
        branch: master